config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/index'

  get 'users/show'

  get 'users/update'

  get 'users/destroy'

  resources :rentals
  resources :calendar_tests
  get '/main_calendar' => 'calendar_tests#index'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'sessions#create'

end

app/models/calendar_test.rb
class CalendarTest < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :rentals 
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/calendar_tests_controller.rb
class CalendarTestsController < ApplicationController
  before_action :set_calendar_test, only: [:show, :edit, :update, :destroy]
  before_filter :authorize


  # GET /calendar_tests
  # GET /calendar_tests.json
  def index
    @calendar_tests = CalendarTest.all
    @rentals =Rental.all 
    # render plain: @rentals
  end

  # GET /calendar_tests/1
  # GET /calendar_tests/1.json
  def show
  end

  # GET /calendar_tests/new
  def new
    @calendar_test = CalendarTest.new
  end

  # GET /calendar_tests/1/edit
  def edit
  end

  # POST /calendar_tests
  # POST /calendar_tests.json
  def create
    @calendar_test = CalendarTest.new(calendar_test_params)

    respond_to do |format|
      if @calendar_test.save
        format.html { redirect_to @calendar_test, notice: 'Calendar test was successfully created.' }
        format.json { render :show, status: :created, location: @calendar_test }
      else
        format.html { render :new }
        format.json { render json: @calendar_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendar_tests/1
  # PATCH/PUT /calendar_tests/1.json
  def update
    respond_to do |format|
      if @calendar_test.update(calendar_test_params)
        format.html { redirect_to @calendar_test, notice: 'Calendar test was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar_test }
      else
        format.html { render :edit }
        format.json { render json: @calendar_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendar_tests/1
  # DELETE /calendar_tests/1.json
  def destroy
    @calendar_test.destroy
    respond_to do |format|
      format.html { redirect_to calendar_tests_url, notice: 'Calendar test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar_test
      @calendar_test = CalendarTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_test_params
      params.require(:calendar_test).permit(:index)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_filter :authorize


  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all

    # render plain: @rentals
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    # render plain: params
    @rental = Rental.new
    @start_date = params[:format]
    # render plain: @start_date

  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user

    # render plain: @rental.user.email

      if @rental.save
        redirect_to calendar_tests_path
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:name, :start_time, :end_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/main_calendar'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def edit
  end

  def index
  end

  def show

    # render plain: params
    @user = User.find(params[:id]||=params[:format])
    @rentals = @user.rentals.all
    # render plain: @user

  end

  def update
  end

  def destroy
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_tests_helper.rb
module CalendarTestsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar_tests/_form.html.erb
<%= form_for(@calendar_test) do |f| %>
  <% if @calendar_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar_test.errors.count, "error") %> prohibited this calendar_test from being saved:</h2>

      <ul>
      <% @calendar_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendar_tests/edit.html.erb
<h1>Editing Calendar Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar_test %> |
<%= link_to 'Back', calendar_tests_path %>

app/views/calendar_tests/index.html.erb
<p id="notice"><%= notice %></p>
<style>
  

  .day{
    background-color: linen;
    border:solid .5px;
  }
  .simple-calendar{
    /*border:solid 2px;*/
    border-top:none;
  }
  .calendar-heading {
    font_size: 50pt;
    color: green;
  }
  .calendar-title{
    font-size: 30px;
  }
  thead {
    background-color: darkgrey;

    border:solid;

  }
</style>

<h1>Reservations Calendar</h1>

------------ <h3>click a date to make a reservation</h3>-----------

<table>


  <tbody>
    <% @calendar_tests.each do |calendar_test| %>
      <tr>
        <td><%= calendar_test.index %></td>
        <td><%= link_to 'Show', calendar_test %></td>
        <td><%= link_to 'Edit', edit_calendar_test_path(calendar_test) %></td>
        <td><%= link_to 'Destroy', calendar_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_rental_path %> <br> <br>






<%= month_calendar events: @rentals do |date, rentals| %>
    <%= link_to date.strftime("%d"), new_rental_path(date) %>
    <% rentals.each do |rental| %>
      <div>
        <h4><%=link_to rental.user.name, users_show_path(rental.user.id) %>: <%= link_to rental.name, rental_path(rental), style: 'color:red;' %></h4>
      </div>
    <% end %>

<% end %>

app/views/calendar_tests/new.html.erb
<h1>New Calendar Test</h1>

<%= render 'form' %>

<%= link_to 'Back', calendar_tests_path %>

app/views/calendar_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @calendar_test.index %>
</p>

<%= link_to 'Edit', edit_calendar_test_path(@calendar_test) %> |
<%= link_to 'Back', calendar_tests_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body background='/assets/background.jpg'>
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %> | <%= link_to 'Users', users_path %> | <%= link_to "Reservations", rentals_path %> | <%=link_to "Main Calendar", calendar_tests_path %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select(:start_time, selected: (@rental.start_time||= @start_date)) %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.date_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit "Create Reservation", data: { confirm: "Your reservation will be created, and your credit card charged." }%>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<style>
  td {
    border: 2px solid black;
    padding: 10px;
  }
</style>


<p id="notice"><%= notice %></p>

<h1>Listing Rentals</h1>

<table style='padding:20px;'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
      <th> Rsv for:</th>
    </tr>
  </thead>

  <tbody >
    <% if @rentals %>
        <% @rentals.each do |rental| %>
          <tr style='padding:60px;'>
            <td><%= rental.name %></td>
            <td style='color:red;padding:3px;'><%= rental.start_time.strftime("%a, %b %d %Y ") %></td>
            <td style='color:red;padding:3px;'><%= rental.end_time.strftime("%a, %b %d %Y ") %></td>
            <td ><%= link_to 'Show', rental %></td>
            <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
            <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td ><%= link_to rental.user.name, user_path(rental.user) %></td>

          </tr>
        <% end %>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Reservation for <%= current_user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Owner:</strong>
  <%= @rental.user.email %>
</p>
<p>
  <strong>Name:</strong>
  <%= @rental.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @rental.start_time.strftime("%a, %b %d %Y ") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @rental.end_time.strftime("%a, %b %d %Y ") %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %> |
<%= link_to 'Cancel Reservation', rental_path(@rental),  :method => 'delete' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %><h1>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<style>
	tr {
		border:solids;
	}
	td {
		border:solid;
		padding:10px;

	}
</style>

<h1><%=@user.name %>'s Rentals:</h1>
<table style='border: solid;padding:30px;'>
<% if @rentals.exists? %>
		<%@rentals.each do |r| %>
			<tr>
				<th>Reservation:</th>

				<th>Start Date: </th>
				<th>End Date:</th>
				<th></th>
				<th></th>
			</tr>
			<tr>
				<td><%=r.name %></td>
				<td><%= r.start_time.strftime("%a, %b %d %Y ") %></td>
				<td><%= r.end_time.strftime("%a, %b %d %Y ") %> </td>
				<td><%= link_to "Delete", rental_path(r), :method => 'delete' %></td>
				<td><%= link_to "Change", edit_rental_path(r)%> </td>

			</tr>





		<% end %>
	</table>
<%else %>
	<%= 'Nope, an error or no rentals.' %>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>